import os

FC=os.environ.get('FC')

fsources = ['sor_routines.f95','sor_params.f95', 'sor_main.f95']


FFLAGS = ['-Wall','-cpp', '-O3','-mcmodel=medium','-m64','-ffree-form','-ffree-line-length-0','-fconvert=little-endian','-frecord-marker=4']

envF=Environment(F95=FC,LINK=FC,F95FLAGS=FFLAGS,F95PATH=['.' ,'/usr/local/include'])

envF.Program('sor',fsources,LIBS=['m'],LIBPATH=['.' ,'/usr/lib','/usr/local/lib'])

